INSERT INTO practice_problems (title, platform, link, difficulty, topic) VALUES
('Weird Algorithm', 'CSES', 'https://cses.fi/problemset/task/1068/', 800, 'implementation'),
('Missing Number', 'CSES', 'https://cses.fi/problemset/task/1083/', 800, 'math'),
('Repetitions', 'CSES', 'https://cses.fi/problemset/task/1069/', 800, 'strings'),
('Increasing Array', 'CSES', 'https://cses.fi/problemset/task/1094/', 800, 'greedy'),
('Permutations', 'CSES', 'https://cses.fi/problemset/task/1070/', 900, 'constructive'),
('Two Knights', 'CSES', 'https://cses.fi/problemset/task/1072/', 900, 'math'),
('Number Spiral', 'CSES', 'https://cses.fi/problemset/task/1071/', 900, 'math'),
('Two Sets', 'CSES', 'https://cses.fi/problemset/task/1092/', 1000, 'greedy'),
('Bit Strings', 'CSES', 'https://cses.fi/problemset/task/1617/', 900, 'math'),
('Trailing Zeros', 'CSES', 'https://cses.fi/problemset/task/1618/', 900, 'math'),
('Beautiful Matrix', 'Codeforces', 'https://codeforces.com/problemset/problem/263/A', 800, 'implementation'),
('Bit++', 'Codeforces', 'https://codeforces.com/problemset/problem/282/A', 800, 'implementation'),
('Team', 'Codeforces', 'https://codeforces.com/problemset/problem/231/A', 800, 'implementation'),
('Next Round', 'Codeforces', 'https://codeforces.com/problemset/problem/158/A', 800, 'implementation'),
('Word Capitalization', 'Codeforces', 'https://codeforces.com/problemset/problem/281/A', 800, 'strings'),
('Nearly Lucky Number', 'Codeforces', 'https://codeforces.com/problemset/problem/110/A', 800, 'math'),
('Stones on the Table', 'Codeforces', 'https://codeforces.com/problemset/problem/266/A', 800, 'strings'),
('Queue at the School', 'Codeforces', 'https://codeforces.com/problemset/problem/266/B', 900, 'simulation'),
('Young Physicist', 'Codeforces', 'https://codeforces.com/problemset/problem/69/A', 900, 'implementation'),
('Elephant', 'Codeforces', 'https://codeforces.com/problemset/problem/617/A', 800, 'greedy'),
('Word', 'Codeforces', 'https://codeforces.com/problemset/problem/59/A', 900, 'strings'),
('Anton and Danik', 'Codeforces', 'https://codeforces.com/problemset/problem/734/A', 800, 'implementation'),
('Helpful Maths', 'Codeforces', 'https://codeforces.com/problemset/problem/339/A', 900, 'sorting'),
('Soldier and Bananas', 'Codeforces', 'https://codeforces.com/problemset/problem/546/A', 800, 'math'),
('Boy or Girl', 'Codeforces', 'https://codeforces.com/problemset/problem/236/A', 800, 'strings'),
('Translation', 'Codeforces', 'https://codeforces.com/problemset/problem/41/A', 900, 'strings'),
('Vanya and Fence', 'Codeforces', 'https://codeforces.com/problemset/problem/677/A', 800, 'implementation'),
('George and Accommodation', 'Codeforces', 'https://codeforces.com/problemset/problem/467/A', 800, 'implementation'),
('Magnets', 'Codeforces', 'https://codeforces.com/problemset/problem/344/A', 800, 'implementation'),
('Presents', 'Codeforces', 'https://codeforces.com/problemset/problem/136/A', 900, 'arrays'),
('Divisibility Problem', 'Codeforces', 'https://codeforces.com/problemset/problem/1328/A', 900, 'math'),
('Tram', 'Codeforces', 'https://codeforces.com/problemset/problem/116/A', 900, 'implementation'),
('Drinks', 'Codeforces', 'https://codeforces.com/problemset/problem/200/B', 800, 'math'),
('HQ9+', 'Codeforces', 'https://codeforces.com/problemset/problem/133/A', 900, 'strings'),
('Even Odds', 'Codeforces', 'https://codeforces.com/problemset/problem/318/A', 1000, 'math'),
('Arrival of the General', 'Codeforces', 'https://codeforces.com/problemset/problem/144/A', 900, 'implementation'),
('Dubstep', 'Codeforces', 'https://codeforces.com/problemset/problem/208/A', 900, 'strings'),
('Lucky Division', 'Codeforces', 'https://codeforces.com/problemset/problem/122/A', 1000, 'math'),
('I Wanna Be the Guy', 'Codeforces', 'https://codeforces.com/problemset/problem/469/A', 800, 'implementation'),
('Petya and Strings', 'Codeforces', 'https://codeforces.com/problemset/problem/112/A', 800, 'strings'),
('Taxi', 'Codeforces', 'https://codeforces.com/problemset/problem/158/B', 1100, 'greedy'),
('Fancy Fence', 'Codeforces', 'https://codeforces.com/problemset/problem/270/A', 1100, 'math'),
('Fence', 'Codeforces', 'https://codeforces.com/problemset/problem/363/B', 1100, 'dp'),
('Laptops', 'Codeforces', 'https://codeforces.com/problemset/problem/456/A', 1100, 'sorting'),
('A and B and Compilation Errors', 'Codeforces', 'https://codeforces.com/problemset/problem/519/B', 1100, 'data structures'),
('Interesting drink', 'Codeforces', 'https://codeforces.com/problemset/problem/706/B', 1100, 'binary search'),
('Sum of Odd Integers', 'Codeforces', 'https://codeforces.com/problemset/problem/1327/A', 1100, 'math'),
('Similar Pairs', 'Codeforces', 'https://codeforces.com/problemset/problem/1360/C', 1100, 'greedy'),
('Ilya and Queries', 'Codeforces', 'https://codeforces.com/problemset/problem/313/B', 1100, 'dp'),
('Sereja and Suffixes', 'Codeforces', 'https://codeforces.com/problemset/problem/368/B', 1100, 'dp'),
('Distinct Numbers', 'CSES', 'https://cses.fi/problemset/task/1621/', 1100, 'sorting'),
('Apartments', 'CSES', 'https://cses.fi/problemset/task/1084/', 1100, 'greedy'),
('Ferris Wheel', 'CSES', 'https://cses.fi/problemset/task/1090/', 1100, 'greedy'),
('Concert Tickets', 'CSES', 'https://cses.fi/problemset/task/1091/', 1200, 'binary search'),
('Restaurant Customers', 'CSES', 'https://cses.fi/problemset/task/1619/', 1200, 'sorting'),
('Vanya and Lanterns', 'Codeforces', 'https://codeforces.com/problemset/problem/492/B', 1200, 'math'),
('Cheap Travel', 'Codeforces', 'https://codeforces.com/problemset/problem/466/A', 1200, 'greedy'),
('BerSU Ball', 'Codeforces', 'https://codeforces.com/problemset/problem/489/B', 1200, 'greedy'),
('K-th Not Divisible by n', 'Codeforces', 'https://codeforces.com/problemset/problem/1352/C', 1200, 'binary search'),
('Alternating Subsequence', 'Codeforces', 'https://codeforces.com/problemset/problem/1343/C', 1200, 'greedy'),
('XXXXX', 'Codeforces', 'https://codeforces.com/problemset/problem/1364/A', 1200, 'math'),
('Ternary XOR', 'Codeforces', 'https://codeforces.com/problemset/problem/1328/C', 1200, 'greedy'),
('Same Differences', 'Codeforces', 'https://codeforces.com/problemset/problem/1520/D', 1200, 'math'),
('Pashmak and Garden', 'Codeforces', 'https://codeforces.com/problemset/problem/459/A', 1200, 'math'),
('Worms', 'Codeforces', 'https://codeforces.com/problemset/problem/474/B', 1200, 'binary search'),
('Flipping Game', 'Codeforces', 'https://codeforces.com/problemset/problem/327/A', 1200, 'dp'),
('Chewbacca and Number', 'Codeforces', 'https://codeforces.com/problemset/problem/514/A', 1200, 'greedy'),
('Less or Equal', 'Codeforces', 'https://codeforces.com/problemset/problem/977/C', 1200, 'sorting'),
('Vanya and Exams', 'Codeforces', 'https://codeforces.com/problemset/problem/492/C', 1200, 'greedy'),
('Cut Ribbon', 'Codeforces', 'https://codeforces.com/problemset/problem/189/A', 1300, 'dp'),
('IQ test', 'Codeforces', 'https://codeforces.com/problemset/problem/25/A', 1300, 'math'),
('Registration system', 'Codeforces', 'https://codeforces.com/problemset/problem/4/C', 1300, 'data structures'),
('T-primes', 'Codeforces', 'https://codeforces.com/problemset/problem/230/B', 1300, 'math'),
('Random Teams', 'Codeforces', 'https://codeforces.com/problemset/problem/478/B', 1300, 'math'),
('Given Length and Sum of Digits...', 'Codeforces', 'https://codeforces.com/problemset/problem/489/C', 1400, 'greedy'),
('Two Buttons', 'Codeforces', 'https://codeforces.com/problemset/problem/520/B', 1400, 'graphs'),
('Books', 'Codeforces', 'https://codeforces.com/problemset/problem/279/B', 1400, 'two pointers'),
('Exams', 'Codeforces', 'https://codeforces.com/problemset/problem/479/C', 1400, 'sorting'),
('Vacations', 'Codeforces', 'https://codeforces.com/problemset/problem/698/A', 1400, 'dp'),
('Movie Festival', 'CSES', 'https://cses.fi/problemset/task/1629/', 1300, 'greedy'),
('Sum of Two Values', 'CSES', 'https://cses.fi/problemset/task/1640/', 1300, 'two pointers'),
('Maximum Subarray Sum', 'CSES', 'https://cses.fi/problemset/task/1643/', 1300, 'dp'),
('Stick Lengths', 'CSES', 'https://cses.fi/problemset/task/1074/', 1300, 'math'),
('Missing Coin Sum', 'CSES', 'https://cses.fi/problemset/task/2183/', 1400, 'greedy'),
('Collecting Numbers', 'CSES', 'https://cses.fi/problemset/task/2216/', 1400, 'arrays'),
('Playlist', 'CSES', 'https://cses.fi/problemset/task/1141/', 1400, 'two pointers'),
('Towers', 'CSES', 'https://cses.fi/problemset/task/1073/', 1400, 'greedy'),
('Traffic Lights', 'CSES', 'https://cses.fi/problemset/task/1163/', 1500, 'data structures'),
('Room Allocation', 'CSES', 'https://cses.fi/problemset/task/1164/', 1500, 'greedy'),
('Factory Machines', 'CSES', 'https://cses.fi/problemset/task/1620/', 1500, 'binary search'),
('Kefa and Company', 'Codeforces', 'https://codeforces.com/problemset/problem/580/B', 1500, 'two pointers'),
('Boredom', 'Codeforces', 'https://codeforces.com/problemset/problem/455/A', 1500, 'dp'),
('Woodcutters', 'Codeforces', 'https://codeforces.com/problemset/problem/545/C', 1500, 'greedy'),
('Cellular Network', 'Codeforces', 'https://codeforces.com/problemset/problem/702/C', 1500, 'binary search'),
('Sanatorium', 'Codeforces', 'https://codeforces.com/problemset/problem/716/B', 1500, 'strings'),
('Two Substrings', 'Codeforces', 'https://codeforces.com/problemset/problem/550/A', 1500, 'greedy'),
('Divisibility by Eight', 'Codeforces', 'https://codeforces.com/problemset/problem/550/C', 1500, 'dp'),
('K-th Beautiful String', 'Codeforces', 'https://codeforces.com/problemset/problem/1328/B', 1500, 'math'),
('Zero Array', 'Codeforces', 'https://codeforces.com/problemset/problem/1201/B', 1500, 'greedy'),
('Potions (Hard Version)', 'Codeforces', 'https://codeforces.com/problemset/problem/1526/C2', 1500, 'data structures'),
('Maze', 'Codeforces', 'https://codeforces.com/problemset/problem/377/A', 1600, 'dfs'),
('Good Subarrays', 'Codeforces', 'https://codeforces.com/problemset/problem/1398/C', 1600, 'data structures'),
('Ice Skating', 'Codeforces', 'https://codeforces.com/problemset/problem/217/A', 1600, 'dfs'),
('Linova and Kingdom', 'Codeforces', 'https://codeforces.com/problemset/problem/1336/A', 1600, 'dfs'),
('Little Girl and Maximum Sum', 'Codeforces', 'https://codeforces.com/problemset/problem/276/C', 1600, 'data structures'),
('Tetrahedron', 'Codeforces', 'https://codeforces.com/problemset/problem/166/E', 1500, 'dp'),
('Learning Languages', 'Codeforces', 'https://codeforces.com/problemset/problem/277/A', 1600, 'dfs'),
('Parsa''s Humongous Tree', 'Codeforces', 'https://codeforces.com/problemset/problem/1529/B', 1600, 'dp'),
('Maximum Absurdity', 'Codeforces', 'https://codeforces.com/problemset/problem/332/B', 1600, 'dp'),
('Fox And Names', 'Codeforces', 'https://codeforces.com/problemset/problem/510/C', 1600, 'graphs'),
('Number of Ways', 'Codeforces', 'https://codeforces.com/problemset/problem/466/C', 1700, 'dp'),
('Caesar''s Legions', 'Codeforces', 'https://codeforces.com/problemset/problem/118/D', 1700, 'dp'),
('Flowers', 'Codeforces', 'https://codeforces.com/problemset/problem/474/D', 1700, 'dp'),
('Color the Fence', 'Codeforces', 'https://codeforces.com/problemset/problem/349/B', 1700, 'greedy'),
('DZY Loves Chemistry', 'Codeforces', 'https://codeforces.com/problemset/problem/445/B', 1700, 'dfs'),
('Greg and Array', 'Codeforces', 'https://codeforces.com/problemset/problem/295/A', 1700, 'data structures'),
('Xenia and Bit Operations', 'Codeforces', 'https://codeforces.com/problemset/problem/339/D', 1700, 'trees'),
('Gargari and Bishops', 'Codeforces', 'https://codeforces.com/problemset/problem/463/C', 1700, 'math'),
('Sleeping Schedule', 'Codeforces', 'https://codeforces.com/problemset/problem/1324/E', 1700, 'dp'),
('Journey', 'Codeforces', 'https://codeforces.com/problemset/problem/839/C', 1700, 'dfs'),
('Tasks and Deadlines', 'CSES', 'https://cses.fi/problemset/task/1630/', 1500, 'greedy'),
('Reading Books', 'CSES', 'https://cses.fi/problemset/task/1631/', 1500, 'greedy'),
('Subarray Sums I', 'CSES', 'https://cses.fi/problemset/task/1660/', 1500, 'two pointers'),
('Subarray Sums II', 'CSES', 'https://cses.fi/problemset/task/1661/', 1600, 'data structures'),
('Subarray Divisibility', 'CSES', 'https://cses.fi/problemset/task/1662/', 1600, 'data structures'),
('Array Division', 'CSES', 'https://cses.fi/problemset/task/1085/', 1600, 'binary search'),
('Sliding Median', 'CSES', 'https://cses.fi/problemset/task/1076/', 1700, 'data structures'),
('Sliding Cost', 'CSES', 'https://cses.fi/problemset/task/1077/', 1700, 'data structures'),
('Building Roads', 'CSES', 'https://cses.fi/problemset/task/1666/', 1500, 'graphs'),
('Message Route', 'CSES', 'https://cses.fi/problemset/task/1667/', 1500, 'graphs'),
('Building Teams', 'CSES', 'https://cses.fi/problemset/task/1668/', 1500, 'graphs'),
('Round Trip', 'CSES', 'https://cses.fi/problemset/task/1669/', 1600, 'graphs'),
('Shortest Routes I', 'CSES', 'https://cses.fi/problemset/task/1671/', 1600, 'graphs'),
('Shortest Routes II', 'CSES', 'https://cses.fi/problemset/task/1672/', 1600, 'graphs'),
('High Score', 'CSES', 'https://cses.fi/problemset/task/1673/', 1700, 'graphs'),
('Flight Discount', 'CSES', 'https://cses.fi/problemset/task/1195/', 1700, 'graphs'),
('Cycle Finding', 'CSES', 'https://cses.fi/problemset/task/1197/', 1700, 'graphs'),
('Flight Routes', 'CSES', 'https://cses.fi/problemset/task/1196/', 1700, 'graphs'),
('Game Routes', 'CSES', 'https://cses.fi/problemset/task/1680/', 1700, 'graphs'),
('Longest Flight Route', 'CSES', 'https://cses.fi/problemset/task/1681/', 1700, 'graphs'),
('Subordinates', 'CSES', 'https://cses.fi/problemset/task/1674/', 1600, 'trees'),
('Tree Matching', 'CSES', 'https://cses.fi/problemset/task/1130/', 1600, 'trees'),
('Tree Diameter', 'CSES', 'https://cses.fi/problemset/task/1131/', 1700, 'trees'),
('Tree Distances I', 'CSES', 'https://cses.fi/problemset/task/1132/', 1700, 'trees'),
('Tree Distances II', 'CSES', 'https://cses.fi/problemset/task/1133/', 1700, 'trees'),
('Company Queries I', 'CSES', 'https://cses.fi/problemset/task/1687/', 1700, 'trees'),
('Company Queries II', 'CSES', 'https://cses.fi/problemset/task/1688/', 1700, 'trees'),
('Distance Queries', 'CSES', 'https://cses.fi/problemset/task/1136/', 1800, 'trees'),
('Planets and Kingdoms', 'CSES', 'https://cses.fi/problemset/task/1683/', 1700, 'graphs'),
('Giant Pizza', 'CSES', 'https://cses.fi/problemset/task/1684/', 1800, 'graphs'),
('Painting Fence', 'Codeforces', 'https://codeforces.com/problemset/problem/448/C', 1700, 'divide and conquer'),
('Code For 1', 'Codeforces', 'https://codeforces.com/problemset/problem/768/B', 1700, 'divide and conquer'),
('Solve The Maze', 'Codeforces', 'https://codeforces.com/problemset/problem/1365/D', 1700, 'dfs'),
('Checkposts', 'Codeforces', 'https://codeforces.com/problemset/problem/427/C', 1700, 'graphs'),
('24 Game', 'Codeforces', 'https://codeforces.com/problemset/problem/468/A', 1700, 'math'),
('Riding in a Lift', 'Codeforces', 'https://codeforces.com/problemset/problem/479/E', 1700, 'dp'),
('Writing Code', 'Codeforces', 'https://codeforces.com/problemset/problem/543/A', 1700, 'dp'),
('Gerald''s Hexagon', 'Codeforces', 'https://codeforces.com/problemset/problem/559/A', 1700, 'math'),
('Approximating a Constant Range', 'Codeforces', 'https://codeforces.com/problemset/problem/602/B', 1700, 'two pointers'),
('Recycling Bottles', 'Codeforces', 'https://codeforces.com/problemset/problem/671/A', 1700, 'greedy'),
('Alyona and the Tree', 'Codeforces', 'https://codeforces.com/problemset/problem/682/C', 1700, 'dfs'),
('Exams', 'Codeforces', 'https://codeforces.com/problemset/problem/732/D', 1700, 'binary search'),
('Multiplicity', 'Codeforces', 'https://codeforces.com/problemset/problem/1061/C', 1700, 'dp'),
('Obtain The String', 'Codeforces', 'https://codeforces.com/problemset/problem/1295/C', 1700, 'strings'),
('Maximum Sum on Even Positions', 'Codeforces', 'https://codeforces.com/problemset/problem/1373/D', 1700, 'dp'),
('Tree Queries', 'Codeforces', 'https://codeforces.com/problemset/problem/1328/E', 1800, 'trees'),
('A/B Matrix', 'Codeforces', 'https://codeforces.com/problemset/problem/1360/G', 1800, 'constructive'),
('Odd-Even Subsequence', 'Codeforces', 'https://codeforces.com/problemset/problem/1370/D', 1800, 'binary search'),
('Reading Books (easy version)', 'Codeforces', 'https://codeforces.com/problemset/problem/1374/E1', 1800, 'greedy'),
('Colored Rectangles', 'Codeforces', 'https://codeforces.com/problemset/problem/1398/D', 1800, 'dp'),
('Binary String Reconstruction', 'Codeforces', 'https://codeforces.com/problemset/problem/1400/C', 1800, 'strings'),
('Zero Remainder Sum', 'Codeforces', 'https://codeforces.com/problemset/problem/1433/F', 1800, 'dp'),
('Number of Simple Paths', 'Codeforces', 'https://codeforces.com/problemset/problem/1454/E', 1800, 'graphs'),
('New Year''s Puzzle', 'Codeforces', 'https://codeforces.com/problemset/problem/1472/F', 1800, 'dp'),
('Old Floppy Drive', 'Codeforces', 'https://codeforces.com/problemset/problem/1490/G', 1800, 'binary search'),
('Education', 'Codeforces', 'https://codeforces.com/problemset/problem/1512/F', 1800, 'greedy'),
('Guess the K-th Zero (Easy version)', 'Codeforces', 'https://codeforces.com/problemset/problem/1520/F1', 1800, 'interactive'),
('Gift Set', 'Codeforces', 'https://codeforces.com/problemset/problem/1538/G', 1800, 'binary search'),
('Fixed Points', 'Codeforces', 'https://codeforces.com/problemset/problem/1551/E', 1800, 'dp'),
('Polycarp and String Transformation', 'Codeforces', 'https://codeforces.com/problemset/problem/1560/E', 1800, 'strings'),
('Static Range Minimum Queries', 'CSES', 'https://cses.fi/problemset/task/1647/', 1500, 'data structures'),
('Dynamic Range Sum Queries', 'CSES', 'https://cses.fi/problemset/task/1648/', 1600, 'data structures'),
('Dynamic Range Minimum Queries', 'CSES', 'https://cses.fi/problemset/task/1649/', 1600, 'data structures'),
('Range Xor Queries', 'CSES', 'https://cses.fi/problemset/task/1650/', 1600, 'data structures'),
('Range Update Queries', 'CSES', 'https://cses.fi/problemset/task/1651/', 1700, 'data structures'),
('Forest Queries', 'CSES', 'https://cses.fi/problemset/task/1652/', 1700, 'data structures'),
('Hotel Queries', 'CSES', 'https://cses.fi/problemset/task/1143/', 1700, 'data structures'),
('List Removals', 'CSES', 'https://cses.fi/problemset/task/1144/', 1800, 'data structures'),
('Salary Queries', 'CSES', 'https://cses.fi/problemset/task/1190/', 1800, 'data structures'),
('Prefix Sum Queries', 'CSES', 'https://cses.fi/problemset/task/1734/', 1800, 'data structures')
ON CONFLICT (link) DO NOTHING;
