export type MetricPoint = {
  label: string;
  value: number;
};

export type LeaderboardRow = {
  rank: number;
  name: string;
  problemsSolved: number;
  score: number;
  streak: number;
};

export type QuestionBankItem = {
  id: number;
  question: string;
  topic: string;
  type: "mcq" | "coding";
  options?: string[];
  languages?: string[];
};

export const studentStats = {
  solved: 126,
  quizAverage: 84,
  weakTopics: ["graphs", "dynamic programming", "bit manipulation"],
  activeQuiz: {
    title: "DSA Mid-Sem Sprint",
    timeLeft: "01h 42m",
    questions: 12,
  },
  previousQuizzes: [
    { title: "Operating Systems Drill", score: 72, date: "Mar 1" },
    { title: "DBMS Quiz", score: 88, date: "Feb 18" },
    { title: "Computer Networks", score: 79, date: "Feb 4" },
  ],
  activity: [
    { label: "Mon", value: 5 },
    { label: "Tue", value: 8 },
    { label: "Wed", value: 3 },
    { label: "Thu", value: 6 },
    { label: "Fri", value: 9 },
    { label: "Sat", value: 4 },
    { label: "Sun", value: 2 },
  ],
  topicAnalysis: [
    { label: "Arrays", value: 90 },
    { label: "Graphs", value: 55 },
    { label: "DP", value: 48 },
    { label: "Greedy", value: 76 },
  ],
  handles: {
    codeforces: "bitwise_ace",
    codechef: "bitjudge",
    leetcode: "bitwise_runner",
    hackerrank: "juet_hacker",
    github: "bitjudge-dev",
  },
};

export const practiceProblems = [
  { id: 1, title: "Weird Algorithm", platform: "CSES", difficulty: 800, topic: "implementation", solved: false, link: "https://cses.fi/problemset/task/1068/" },
  { id: 2, title: "Missing Number", platform: "CSES", difficulty: 800, topic: "math", solved: false, link: "https://cses.fi/problemset/task/1083/" },
  { id: 3, title: "Repetitions", platform: "CSES", difficulty: 800, topic: "strings", solved: false, link: "https://cses.fi/problemset/task/1069/" },
  { id: 4, title: "Increasing Array", platform: "CSES", difficulty: 800, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1094/" },
  { id: 5, title: "Permutations", platform: "CSES", difficulty: 900, topic: "constructive", solved: false, link: "https://cses.fi/problemset/task/1070/" },
  { id: 6, title: "Two Knights", platform: "CSES", difficulty: 900, topic: "math", solved: false, link: "https://cses.fi/problemset/task/1072/" },
  { id: 7, title: "Number Spiral", platform: "CSES", difficulty: 900, topic: "math", solved: false, link: "https://cses.fi/problemset/task/1071/" },
  { id: 8, title: "Two Sets", platform: "CSES", difficulty: 1000, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1092/" },
  { id: 9, title: "Bit Strings", platform: "CSES", difficulty: 900, topic: "math", solved: false, link: "https://cses.fi/problemset/task/1617/" },
  { id: 10, title: "Trailing Zeros", platform: "CSES", difficulty: 900, topic: "math", solved: false, link: "https://cses.fi/problemset/task/1618/" },
  { id: 11, title: "Beautiful Matrix", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/263/A" },
  { id: 12, title: "Bit++", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/282/A" },
  { id: 13, title: "Team", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/231/A" },
  { id: 14, title: "Next Round", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/158/A" },
  { id: 15, title: "Word Capitalization", platform: "Codeforces", difficulty: 800, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/281/A" },
  { id: 16, title: "Nearly Lucky Number", platform: "Codeforces", difficulty: 800, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/110/A" },
  { id: 17, title: "Stones on the Table", platform: "Codeforces", difficulty: 800, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/266/A" },
  { id: 18, title: "Queue at the School", platform: "Codeforces", difficulty: 900, topic: "simulation", solved: false, link: "https://codeforces.com/problemset/problem/266/B" },
  { id: 19, title: "Young Physicist", platform: "Codeforces", difficulty: 900, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/69/A" },
  { id: 20, title: "Elephant", platform: "Codeforces", difficulty: 800, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/617/A" },
  { id: 21, title: "Word", platform: "Codeforces", difficulty: 900, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/59/A" },
  { id: 22, title: "Anton and Danik", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/734/A" },
  { id: 23, title: "Helpful Maths", platform: "Codeforces", difficulty: 900, topic: "sorting", solved: false, link: "https://codeforces.com/problemset/problem/339/A" },
  { id: 24, title: "Soldier and Bananas", platform: "Codeforces", difficulty: 800, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/546/A" },
  { id: 25, title: "Boy or Girl", platform: "Codeforces", difficulty: 800, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/236/A" },
  { id: 26, title: "Translation", platform: "Codeforces", difficulty: 900, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/41/A" },
  { id: 27, title: "Vanya and Fence", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/677/A" },
  { id: 28, title: "George and Accommodation", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/467/A" },
  { id: 29, title: "Magnets", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/344/A" },
  { id: 30, title: "Presents", platform: "Codeforces", difficulty: 900, topic: "arrays", solved: false, link: "https://codeforces.com/problemset/problem/136/A" },
  { id: 31, title: "Divisibility Problem", platform: "Codeforces", difficulty: 900, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/1328/A" },
  { id: 32, title: "Tram", platform: "Codeforces", difficulty: 900, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/116/A" },
  { id: 33, title: "Drinks", platform: "Codeforces", difficulty: 800, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/200/B" },
  { id: 34, title: "HQ9+", platform: "Codeforces", difficulty: 900, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/133/A" },
  { id: 35, title: "Even Odds", platform: "Codeforces", difficulty: 1000, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/318/A" },
  { id: 36, title: "Arrival of the General", platform: "Codeforces", difficulty: 900, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/144/A" },
  { id: 37, title: "Dubstep", platform: "Codeforces", difficulty: 900, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/208/A" },
  { id: 38, title: "Lucky Division", platform: "Codeforces", difficulty: 1000, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/122/A" },
  { id: 39, title: "I Wanna Be the Guy", platform: "Codeforces", difficulty: 800, topic: "implementation", solved: false, link: "https://codeforces.com/problemset/problem/469/A" },
  { id: 40, title: "Petya and Strings", platform: "Codeforces", difficulty: 800, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/112/A" },
  { id: 91, title: "Taxi", platform: "Codeforces", difficulty: 1100, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/158/B" },
  { id: 92, title: "Fancy Fence", platform: "Codeforces", difficulty: 1100, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/270/A" },
  { id: 93, title: "Fence", platform: "Codeforces", difficulty: 1100, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/363/B" },
  { id: 94, title: "Laptops", platform: "Codeforces", difficulty: 1100, topic: "sorting", solved: false, link: "https://codeforces.com/problemset/problem/456/A" },
  { id: 95, title: "A and B and Compilation Errors", platform: "Codeforces", difficulty: 1100, topic: "data structures", solved: false, link: "https://codeforces.com/problemset/problem/519/B" },
  { id: 96, title: "Interesting drink", platform: "Codeforces", difficulty: 1100, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/706/B" },
  { id: 97, title: "Sum of Odd Integers", platform: "Codeforces", difficulty: 1100, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/1327/A" },
  { id: 98, title: "Similar Pairs", platform: "Codeforces", difficulty: 1100, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/1360/C" },
  { id: 99, title: "Ilya and Queries", platform: "Codeforces", difficulty: 1100, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/313/B" },
  { id: 100, title: "Sereja and Suffixes", platform: "Codeforces", difficulty: 1100, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/368/B" },
  { id: 101, title: "Distinct Numbers", platform: "CSES", difficulty: 1100, topic: "sorting", solved: false, link: "https://cses.fi/problemset/task/1621/" },
  { id: 102, title: "Apartments", platform: "CSES", difficulty: 1100, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1084/" },
  { id: 103, title: "Ferris Wheel", platform: "CSES", difficulty: 1100, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1090/" },
  { id: 104, title: "Concert Tickets", platform: "CSES", difficulty: 1200, topic: "binary search", solved: false, link: "https://cses.fi/problemset/task/1091/" },
  { id: 105, title: "Restaurant Customers", platform: "CSES", difficulty: 1200, topic: "sorting", solved: false, link: "https://cses.fi/problemset/task/1619/" },
  { id: 106, title: "Vanya and Lanterns", platform: "Codeforces", difficulty: 1200, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/492/B" },
  { id: 107, title: "Cheap Travel", platform: "Codeforces", difficulty: 1200, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/466/A" },
  { id: 108, title: "BerSU Ball", platform: "Codeforces", difficulty: 1200, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/489/B" },
  { id: 109, title: "K-th Not Divisible by n", platform: "Codeforces", difficulty: 1200, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/1352/C" },
  { id: 110, title: "Alternating Subsequence", platform: "Codeforces", difficulty: 1200, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/1343/C" },
  { id: 111, title: "XXXXX", platform: "Codeforces", difficulty: 1200, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/1364/A" },
  { id: 112, title: "Ternary XOR", platform: "Codeforces", difficulty: 1200, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/1328/C" },
  { id: 113, title: "Same Differences", platform: "Codeforces", difficulty: 1200, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/1520/D" },
  { id: 114, title: "Pashmak and Garden", platform: "Codeforces", difficulty: 1200, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/459/A" },
  { id: 115, title: "Worms", platform: "Codeforces", difficulty: 1200, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/474/B" },
  { id: 116, title: "Flipping Game", platform: "Codeforces", difficulty: 1200, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/327/A" },
  { id: 117, title: "Chewbacca and Number", platform: "Codeforces", difficulty: 1200, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/514/A" },
  { id: 118, title: "Less or Equal", platform: "Codeforces", difficulty: 1200, topic: "sorting", solved: false, link: "https://codeforces.com/problemset/problem/977/C" },
  { id: 119, title: "Vanya and Exams", platform: "Codeforces", difficulty: 1200, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/492/C" },
  { id: 120, title: "Cut Ribbon", platform: "Codeforces", difficulty: 1300, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/189/A" },
  { id: 121, title: "IQ test", platform: "Codeforces", difficulty: 1300, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/25/A" },
  { id: 122, title: "Registration system", platform: "Codeforces", difficulty: 1300, topic: "data structures", solved: false, link: "https://codeforces.com/problemset/problem/4/C" },
  { id: 123, title: "T-primes", platform: "Codeforces", difficulty: 1300, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/230/B" },
  { id: 124, title: "Random Teams", platform: "Codeforces", difficulty: 1300, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/478/B" },
  { id: 125, title: "Given Length and Sum of Digits...", platform: "Codeforces", difficulty: 1400, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/489/C" },
  { id: 126, title: "Two Buttons", platform: "Codeforces", difficulty: 1400, topic: "graphs", solved: false, link: "https://codeforces.com/problemset/problem/520/B" },
  { id: 127, title: "Books", platform: "Codeforces", difficulty: 1400, topic: "two pointers", solved: false, link: "https://codeforces.com/problemset/problem/279/B" },
  { id: 128, title: "Exams", platform: "Codeforces", difficulty: 1400, topic: "sorting", solved: false, link: "https://codeforces.com/problemset/problem/479/C" },
  { id: 129, title: "Vacations", platform: "Codeforces", difficulty: 1400, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/698/A" },
  { id: 130, title: "Movie Festival", platform: "CSES", difficulty: 1300, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1629/" },
  { id: 131, title: "Sum of Two Values", platform: "CSES", difficulty: 1300, topic: "two pointers", solved: false, link: "https://cses.fi/problemset/task/1640/" },
  { id: 132, title: "Maximum Subarray Sum", platform: "CSES", difficulty: 1300, topic: "dp", solved: false, link: "https://cses.fi/problemset/task/1643/" },
  { id: 133, title: "Stick Lengths", platform: "CSES", difficulty: 1300, topic: "math", solved: false, link: "https://cses.fi/problemset/task/1074/" },
  { id: 134, title: "Missing Coin Sum", platform: "CSES", difficulty: 1400, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/2183/" },
  { id: 135, title: "Collecting Numbers", platform: "CSES", difficulty: 1400, topic: "arrays", solved: false, link: "https://cses.fi/problemset/task/2216/" },
  { id: 136, title: "Playlist", platform: "CSES", difficulty: 1400, topic: "two pointers", solved: false, link: "https://cses.fi/problemset/task/1141/" },
  { id: 137, title: "Towers", platform: "CSES", difficulty: 1400, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1073/" },
  { id: 138, title: "Traffic Lights", platform: "CSES", difficulty: 1500, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1163/" },
  { id: 139, title: "Room Allocation", platform: "CSES", difficulty: 1500, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1164/" },
  { id: 140, title: "Factory Machines", platform: "CSES", difficulty: 1500, topic: "binary search", solved: false, link: "https://cses.fi/problemset/task/1620/" },
  { id: 141, title: "Kefa and Company", platform: "Codeforces", difficulty: 1500, topic: "two pointers", solved: false, link: "https://codeforces.com/problemset/problem/580/B" },
  { id: 142, title: "Boredom", platform: "Codeforces", difficulty: 1500, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/455/A" },
  { id: 143, title: "Woodcutters", platform: "Codeforces", difficulty: 1500, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/545/C" },
  { id: 144, title: "Cellular Network", platform: "Codeforces", difficulty: 1500, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/702/C" },
  { id: 145, title: "Sanatorium", platform: "Codeforces", difficulty: 1500, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/716/B" },
  { id: 146, title: "Two Substrings", platform: "Codeforces", difficulty: 1500, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/550/A" },
  { id: 147, title: "Divisibility by Eight", platform: "Codeforces", difficulty: 1500, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/550/C" },
  { id: 148, title: "K-th Beautiful String", platform: "Codeforces", difficulty: 1500, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/1328/B" },
  { id: 149, title: "Zero Array", platform: "Codeforces", difficulty: 1500, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/1201/B" },
  { id: 150, title: "Potions (Hard Version)", platform: "Codeforces", difficulty: 1500, topic: "data structures", solved: false, link: "https://codeforces.com/problemset/problem/1526/C2" },
  { id: 151, title: "Maze", platform: "Codeforces", difficulty: 1600, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/377/A" },
  { id: 152, title: "Good Subarrays", platform: "Codeforces", difficulty: 1600, topic: "data structures", solved: false, link: "https://codeforces.com/problemset/problem/1398/C" },
  { id: 153, title: "Ice Skating", platform: "Codeforces", difficulty: 1600, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/217/A" },
  { id: 154, title: "Linova and Kingdom", platform: "Codeforces", difficulty: 1600, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/1336/A" },
  { id: 155, title: "Little Girl and Maximum Sum", platform: "Codeforces", difficulty: 1600, topic: "data structures", solved: false, link: "https://codeforces.com/problemset/problem/276/C" },
  { id: 156, title: "Tetrahedron", platform: "Codeforces", difficulty: 1500, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/166/E" },
  { id: 157, title: "Learning Languages", platform: "Codeforces", difficulty: 1600, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/277/A" },
  { id: 158, title: "Parsa's Humongous Tree", platform: "Codeforces", difficulty: 1600, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1529/B" },
  { id: 159, title: "Maximum Absurdity", platform: "Codeforces", difficulty: 1600, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/332/B" },
  { id: 160, title: "Fox And Names", platform: "Codeforces", difficulty: 1600, topic: "graphs", solved: false, link: "https://codeforces.com/problemset/problem/510/C" },
  { id: 161, title: "Number of Ways", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/466/C" },
  { id: 162, title: "Caesar's Legions", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/118/D" },
  { id: 163, title: "Flowers", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/474/D" },
  { id: 164, title: "Color the Fence", platform: "Codeforces", difficulty: 1700, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/349/B" },
  { id: 165, title: "DZY Loves Chemistry", platform: "Codeforces", difficulty: 1700, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/445/B" },
  { id: 166, title: "Greg and Array", platform: "Codeforces", difficulty: 1700, topic: "data structures", solved: false, link: "https://codeforces.com/problemset/problem/295/A" },
  { id: 167, title: "Xenia and Bit Operations", platform: "Codeforces", difficulty: 1700, topic: "trees", solved: false, link: "https://codeforces.com/problemset/problem/339/D" },
  { id: 168, title: "Gargari and Bishops", platform: "Codeforces", difficulty: 1700, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/463/C" },
  { id: 169, title: "Sleeping Schedule", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1324/E" },
  { id: 170, title: "Journey", platform: "Codeforces", difficulty: 1700, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/839/C" },
  { id: 171, title: "Tasks and Deadlines", platform: "CSES", difficulty: 1500, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1630/" },
  { id: 172, title: "Reading Books", platform: "CSES", difficulty: 1500, topic: "greedy", solved: false, link: "https://cses.fi/problemset/task/1631/" },
  { id: 173, title: "Subarray Sums I", platform: "CSES", difficulty: 1500, topic: "two pointers", solved: false, link: "https://cses.fi/problemset/task/1660/" },
  { id: 174, title: "Subarray Sums II", platform: "CSES", difficulty: 1600, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1661/" },
  { id: 175, title: "Subarray Divisibility", platform: "CSES", difficulty: 1600, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1662/" },
  { id: 176, title: "Array Division", platform: "CSES", difficulty: 1600, topic: "binary search", solved: false, link: "https://cses.fi/problemset/task/1085/" },
  { id: 177, title: "Sliding Median", platform: "CSES", difficulty: 1700, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1076/" },
  { id: 178, title: "Sliding Cost", platform: "CSES", difficulty: 1700, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1077/" },
  { id: 179, title: "Building Roads", platform: "CSES", difficulty: 1500, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1666/" },
  { id: 180, title: "Message Route", platform: "CSES", difficulty: 1500, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1667/" },
  { id: 181, title: "Building Teams", platform: "CSES", difficulty: 1500, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1668/" },
  { id: 182, title: "Round Trip", platform: "CSES", difficulty: 1600, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1669/" },
  { id: 183, title: "Shortest Routes I", platform: "CSES", difficulty: 1600, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1671/" },
  { id: 184, title: "Shortest Routes II", platform: "CSES", difficulty: 1600, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1672/" },
  { id: 185, title: "High Score", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1673/" },
  { id: 186, title: "Flight Discount", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1195/" },
  { id: 187, title: "Cycle Finding", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1197/" },
  { id: 188, title: "Flight Routes", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1196/" },
  { id: 189, title: "Game Routes", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1680/" },
  { id: 190, title: "Longest Flight Route", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1681/" },
  { id: 191, title: "Subordinates", platform: "CSES", difficulty: 1600, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1674/" },
  { id: 192, title: "Tree Matching", platform: "CSES", difficulty: 1600, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1130/" },
  { id: 193, title: "Tree Diameter", platform: "CSES", difficulty: 1700, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1131/" },
  { id: 194, title: "Tree Distances I", platform: "CSES", difficulty: 1700, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1132/" },
  { id: 195, title: "Tree Distances II", platform: "CSES", difficulty: 1700, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1133/" },
  { id: 196, title: "Company Queries I", platform: "CSES", difficulty: 1700, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1687/" },
  { id: 197, title: "Company Queries II", platform: "CSES", difficulty: 1700, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1688/" },
  { id: 198, title: "Distance Queries", platform: "CSES", difficulty: 1800, topic: "trees", solved: false, link: "https://cses.fi/problemset/task/1136/" },
  { id: 199, title: "Planets and Kingdoms", platform: "CSES", difficulty: 1700, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1683/" },
  { id: 200, title: "Giant Pizza", platform: "CSES", difficulty: 1800, topic: "graphs", solved: false, link: "https://cses.fi/problemset/task/1684/" },
  { id: 201, title: "Painting Fence", platform: "Codeforces", difficulty: 1700, topic: "divide and conquer", solved: false, link: "https://codeforces.com/problemset/problem/448/C" },
  { id: 202, title: "Code For 1", platform: "Codeforces", difficulty: 1700, topic: "divide and conquer", solved: false, link: "https://codeforces.com/problemset/problem/768/B" },
  { id: 203, title: "Solve The Maze", platform: "Codeforces", difficulty: 1700, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/1365/D" },
  { id: 204, title: "Checkposts", platform: "Codeforces", difficulty: 1700, topic: "graphs", solved: false, link: "https://codeforces.com/problemset/problem/427/C" },
  { id: 205, title: "24 Game", platform: "Codeforces", difficulty: 1700, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/468/A" },
  { id: 206, title: "Riding in a Lift", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/479/E" },
  { id: 207, title: "Writing Code", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/543/A" },
  { id: 208, title: "Gerald's Hexagon", platform: "Codeforces", difficulty: 1700, topic: "math", solved: false, link: "https://codeforces.com/problemset/problem/559/A" },
  { id: 209, title: "Approximating a Constant Range", platform: "Codeforces", difficulty: 1700, topic: "two pointers", solved: false, link: "https://codeforces.com/problemset/problem/602/B" },
  { id: 210, title: "Recycling Bottles", platform: "Codeforces", difficulty: 1700, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/671/A" },
  { id: 211, title: "Alyona and the Tree", platform: "Codeforces", difficulty: 1700, topic: "dfs", solved: false, link: "https://codeforces.com/problemset/problem/682/C" },
  { id: 212, title: "Exams", platform: "Codeforces", difficulty: 1700, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/732/D" },
  { id: 213, title: "Multiplicity", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1061/C" },
  { id: 214, title: "Obtain The String", platform: "Codeforces", difficulty: 1700, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/1295/C" },
  { id: 215, title: "Maximum Sum on Even Positions", platform: "Codeforces", difficulty: 1700, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1373/D" },
  { id: 216, title: "Tree Queries", platform: "Codeforces", difficulty: 1800, topic: "trees", solved: false, link: "https://codeforces.com/problemset/problem/1328/E" },
  { id: 217, title: "A/B Matrix", platform: "Codeforces", difficulty: 1800, topic: "constructive", solved: false, link: "https://codeforces.com/problemset/problem/1360/G" },
  { id: 218, title: "Odd-Even Subsequence", platform: "Codeforces", difficulty: 1800, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/1370/D" },
  { id: 219, title: "Reading Books (easy version)", platform: "Codeforces", difficulty: 1800, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/1374/E1" },
  { id: 220, title: "Colored Rectangles", platform: "Codeforces", difficulty: 1800, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1398/D" },
  { id: 221, title: "Binary String Reconstruction", platform: "Codeforces", difficulty: 1800, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/1400/C" },
  { id: 222, title: "Zero Remainder Sum", platform: "Codeforces", difficulty: 1800, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1433/F" },
  { id: 223, title: "Number of Simple Paths", platform: "Codeforces", difficulty: 1800, topic: "graphs", solved: false, link: "https://codeforces.com/problemset/problem/1454/E" },
  { id: 224, title: "New Year's Puzzle", platform: "Codeforces", difficulty: 1800, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1472/F" },
  { id: 225, title: "Old Floppy Drive", platform: "Codeforces", difficulty: 1800, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/1490/G" },
  { id: 226, title: "Education", platform: "Codeforces", difficulty: 1800, topic: "greedy", solved: false, link: "https://codeforces.com/problemset/problem/1512/F" },
  { id: 227, title: "Guess the K-th Zero (Easy version)", platform: "Codeforces", difficulty: 1800, topic: "interactive", solved: false, link: "https://codeforces.com/problemset/problem/1520/F1" },
  { id: 228, title: "Gift Set", platform: "Codeforces", difficulty: 1800, topic: "binary search", solved: false, link: "https://codeforces.com/problemset/problem/1538/G" },
  { id: 229, title: "Fixed Points", platform: "Codeforces", difficulty: 1800, topic: "dp", solved: false, link: "https://codeforces.com/problemset/problem/1551/E" },
  { id: 230, title: "Polycarp and String Transformation", platform: "Codeforces", difficulty: 1800, topic: "strings", solved: false, link: "https://codeforces.com/problemset/problem/1560/E" },
  { id: 231, title: "Static Range Minimum Queries", platform: "CSES", difficulty: 1500, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1647/" },
  { id: 232, title: "Dynamic Range Sum Queries", platform: "CSES", difficulty: 1600, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1648/" },
  { id: 233, title: "Dynamic Range Minimum Queries", platform: "CSES", difficulty: 1600, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1649/" },
  { id: 234, title: "Range Xor Queries", platform: "CSES", difficulty: 1600, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1650/" },
  { id: 235, title: "Range Update Queries", platform: "CSES", difficulty: 1700, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1651/" },
  { id: 236, title: "Forest Queries", platform: "CSES", difficulty: 1700, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1652/" },
  { id: 237, title: "Hotel Queries", platform: "CSES", difficulty: 1700, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1143/" },
  { id: 238, title: "List Removals", platform: "CSES", difficulty: 1800, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1144/" },
  { id: 239, title: "Salary Queries", platform: "CSES", difficulty: 1800, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1190/" },
  { id: 240, title: "Prefix Sum Queries", platform: "CSES", difficulty: 1800, topic: "data structures", solved: false, link: "https://cses.fi/problemset/task/1734/" },
];

export const leaderboardRows: LeaderboardRow[] = [
  { rank: 1, name: "Aditi Sharma", problemsSolved: 412, score: 2840, streak: 34 },
  { rank: 2, name: "Rohan Gupta", problemsSolved: 405, score: 2790, streak: 29 },
  { rank: 3, name: "Mehul Jain", problemsSolved: 397, score: 2710, streak: 22 },
  { rank: 4, name: "Priyansh Verma", problemsSolved: 381, score: 2550, streak: 18 },
  { rank: 5, name: "Kritika Singh", problemsSolved: 374, score: 2495, streak: 16 },
  { rank: 6, name: "Harsh Agrawal", problemsSolved: 362, score: 2410, streak: 14 },
  { rank: 7, name: "Ananya Tiwari", problemsSolved: 351, score: 2360, streak: 12 },
  { rank: 8, name: "Yash Raj", problemsSolved: 344, score: 2290, streak: 10 },
  { rank: 9, name: "Sneha Dubey", problemsSolved: 331, score: 2215, streak: 8 },
  { rank: 10, name: "Arpit Mishra", problemsSolved: 325, score: 2160, streak: 7 },
  { rank: 11, name: "Devansh Patel", problemsSolved: 316, score: 2090, streak: 6 },
  { rank: 12, name: "Ishita Saxena", problemsSolved: 309, score: 2055, streak: 5 },
];

export const adminStats = {
  totalUsers: 842,
  totalProblems: 1286,
  totalSubmissions: 18420,
  activeQuiz: "Weekly DSA Arena",
  activeUsers: 417,
  liveQuizParticipants: 268,
  completionRate: 74,
  submissionsTrend: [
    { label: "Mon", value: 1800 },
    { label: "Tue", value: 2140 },
    { label: "Wed", value: 1960 },
    { label: "Thu", value: 2410 },
    { label: "Fri", value: 2675 },
    { label: "Sat", value: 2230 },
    { label: "Sun", value: 2050 },
  ],
  moduleDistribution: [
    { label: "Users", value: 842 },
    { label: "Problems", value: 1286 },
    { label: "Quizzes", value: 54 },
    { label: "Submissions", value: 18420 },
  ],
  topUsers: [
    { name: "Aditi Sharma", score: 2840, solved: 412 },
    { name: "Rohan Gupta", score: 2790, solved: 405 },
    { name: "Mehul Jain", score: 2710, solved: 397 },
    { name: "Priyansh Verma", score: 2550, solved: 381 },
  ],
  systemStats: [
    { label: "API Latency", value: "84 ms" },
    { label: "Judge Queue", value: "27 jobs" },
    { label: "Redis Hit Rate", value: "92%" },
    { label: "DB Pool Usage", value: "61%" },
  ],
};

export const questionBank: QuestionBankItem[] = [
  {
    id: 101,
    question: "Which data structure is used for BFS traversal?",
    topic: "graphs",
    type: "mcq",
    options: ["Stack", "Queue", "Heap", "Deque"],
  },
  {
    id: 102,
    question: "What is the time complexity of binary search?",
    topic: "binary search",
    type: "mcq",
    options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
  },
  {
    id: 201,
    question: "Implement Dijkstra shortest path for a weighted graph.",
    topic: "graphs",
    type: "coding",
    languages: ["C++", "Java", "Python", "C"],
  },
  {
    id: 202,
    question: "Given an array, return the maximum subarray sum.",
    topic: "dp",
    type: "coding",
    languages: ["C++", "Java", "Python", "C"],
  },
];
